#!/usr/bin/env python3

import icalendar
import sys

def print_cal(input_file, output_file):
    details = icalendar.Calendar.from_ical(input_file.read())
    for component in details.walk():
        if component.name != "VEVENT":
            continue

        summary   = component.get("summary")
        start     = component.get("dtstart").dt
        end       = component.get("dtend").dt
        uid       = component.get("uid")
        location  = component.get("location")
        attendees = component.get("attendee")

        print(
            f"{start.month}/{start.day}\t{summary}",
            f"\tfrom {start.hour:02d}:{start.minute:02d}",
            f"\tto {end.hour:02d}:{end.minute:02d}",
            f"\tlocation {location}",
            sep="\n", file=output_file
        )
        print(
            *(f"\tattendees {a}" for a in (attendees or [])),
            sep="\n", file=output_file
        )
        print(
            f"\t/* {uid} */",
            sep="\n", file=output_file
        )

if len(sys.argv) > 1:
    with open(sys.argv[1], "rt", encoding="UTF-8") as f:
        print_cal(f, sys.stdout)
else:
    print_cal(sys.stdin, sys.stdout)
