#!/bin/bash
# https://github.com/Ceryn/img
# Call with '-s' to target only a selection of the screen.

clientid='3e7a4deb7ac67da'
img=$(mktemp '/home/malaniz/rfs/img-XXXXXX.png')

scrot -s -z "$@" $img >/dev/null 2>&1 || exit
res=$(curl -sH "Authorization: Client-ID $clientid" -F "image=@$img" "https://api.imgur.com/3/upload")
