#!/usr/bin/bash

WLAN=wlp3s0
ETH=enp0s25
ETH_IP=10.10.10.20/24

sudo sysctl net.ipv4.ip_forward=1

sudo ip link set $ETH up
sudo ip addr add $ETH_IP dev $ETH
sudo iptables -t nat -A POSTROUTING -o $WLAN -j MASQUERADE
sudo iptables -A FORWARD -i $ETH -o $WLAN -j ACCEPT
sudo iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT



