setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
[ $(hostname) = yoga ] && synergyc ryzen
dunst &!

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec spectrwm
